from PythonClient import *

#a small function to take photos and save them with name py[index].png to folder temp

def SaveBonePositions(index, bones, f_output):
    line = str(index)+"\t"+str(bones.dronePos[b'x_val'])+"\t"+str(bones.dronePos[b'y_val'])+"\t"+str(bones.dronePos[b'z_val'])+"\t"+str(bones.droneOrient[b'x_val'])+"\t"+str(bones.droneOrient[b'y_val'])+"\t"+str(bones.droneOrient[b'z_val'])+"\t"+str(bones.hip[b'x_val'])+"\t"+str(bones.hip[b'y_val'])+"\t"+str(bones.hip[b'z_val'])+"\t"+str(bones.right_up_leg[b'x_val'])+"\t"+str(bones.right_up_leg[b'y_val'])+"\t"+str(bones.right_up_leg[b'z_val'])+"\t"+str(bones.right_leg[b'x_val'])+"\t"+str(bones.right_leg[b'y_val'])+"\t"+str(bones.right_leg[b'z_val'])+"\t"+str(bones.right_foot[b'x_val'])+"\t"+str(bones.right_foot[b'y_val'])+"\t"+str(bones.right_foot[b'z_val'])+"\t"+str(bones.left_up_leg[b'x_val'])+"\t"+str(bones.left_up_leg[b'y_val'])+"\t"+str(bones.left_up_leg[b'z_val'])+"\t"+str(bones.left_leg[b'x_val'])+"\t"+str(bones.left_leg[b'y_val'])+"\t"+str(bones.left_leg[b'z_val'])+"\t"+str(bones.left_foot[b'x_val'])+"\t"+str(bones.left_foot[b'y_val'])+"\t"+str(bones.left_foot[b'z_val'])+"\t"+str(bones.spine1[b'x_val'])+"\t"+str(bones.spine1[b'y_val'])+"\t"+str(bones.spine1[b'z_val'])+"\t"+str(bones.neck[b'x_val'])+"\t"+str(bones.neck[b'y_val'])+"\t"+str(bones.neck[b'z_val'])+"\t"+str(bones.head[b'x_val'])+"\t"+str(bones.head[b'y_val'])+"\t"+str(bones.head[b'z_val'])+"\t"+str(bones.left_arm[b'x_val'])+"\t"+str(bones.left_arm[b'y_val'])+"\t"+str(bones.left_arm[b'z_val'])+"\t"+str(bones.left_forearm[b'x_val'])+"\t"+str(bones.left_forearm[b'y_val'])+"\t"+str(bones.left_forearm[b'z_val'])+"\t"+str(bones.left_hand[b'x_val'])+"\t"+str(bones.left_hand[b'y_val'])+"\t"+str(bones.left_hand[b'z_val'])+"\t"+str(bones.right_arm[b'x_val'])+"\t"+str(bones.right_arm[b'y_val'])+"\t"+str(bones.right_arm[b'z_val'])+"\t"+str(bones.right_forearm[b'x_val'])+"\t"+str(bones.right_forearm[b'y_val'])+"\t"+str(bones.right_forearm[b'z_val'])+"\t"+str(bones.right_hand[b'x_val'])+"\t"+str(bones.right_hand[b'y_val'])+"\t"+str(bones.right_hand[b'z_val'])+"\t"+str(bones.right_hand_tip[b'x_val'])+"\t"+str(bones.right_hand_tip[b'y_val'])+"\t"+str(bones.right_hand_tip[b'z_val'])+"\t"+str(bones.left_hand_tip[b'x_val'])+"\t"+str(bones.left_hand_tip[b'y_val'])+"\t"+str(bones.left_hand_tip[b'z_val'])+"\t"+str(bones.right_foot_tip[b'x_val'])+"\t"+str(bones.right_foot_tip[b'y_val'])+"\t"+str(bones.right_foot_tip[b'z_val'])+"\t"+str(bones.left_foot_tip[b'x_val'])+"\t"+str(bones.left_foot_tip[b'y_val'])+"\t"+str(bones.left_foot_tip[b'z_val'])+"\n"
    f_output.write(line)

def SaveBonePositions2(index, bones, f_output):
    line = str(index)+"\t"+str(bones.dronePos.x_val)+"\t"+str(bones.dronePos.y_val)+"\t"+str(bones.dronePos.z_val)+"\t"+str(bones.droneOrient.x_val)+"\t"+str(bones.droneOrient.y_val)+"\t"+str(bones.droneOrient.z_val)+"\t"+str(bones.hip.x_val)+"\t"+str(bones.hip.y_val)+"\t"+str(bones.hip.z_val)+"\t"+str(bones.right_up_leg.x_val)+"\t"+str(bones.right_up_leg.y_val)+"\t"+str(bones.right_up_leg.z_val)+"\t"+str(bones.right_leg.x_val)+"\t"+str(bones.right_leg.y_val)+"\t"+str(bones.right_leg.z_val)+"\t"+str(bones.right_foot.x_val)+"\t"+str(bones.right_foot.y_val)+"\t"+str(bones.right_foot.z_val)+"\t"+str(bones.left_up_leg.x_val)+"\t"+str(bones.left_up_leg.y_val)+"\t"+str(bones.left_up_leg.z_val)+"\t"+str(bones.left_leg.x_val)+"\t"+str(bones.left_leg.y_val)+"\t"+str(bones.left_leg.z_val)+"\t"+str(bones.left_foot.x_val)+"\t"+str(bones.left_foot.y_val)+"\t"+str(bones.left_foot.z_val)+"\t"+str(bones.spine1.x_val)+"\t"+str(bones.spine1.y_val)+"\t"+str(bones.spine1.z_val)+"\t"+str(bones.neck.x_val)+"\t"+str(bones.neck.y_val)+"\t"+str(bones.neck.z_val)+"\t"+str(bones.head.x_val)+"\t"+str(bones.head.y_val)+"\t"+str(bones.head.z_val)+"\t"+str(bones.left_arm.x_val)+"\t"+str(bones.left_arm.y_val)+"\t"+str(bones.left_arm.z_val)+"\t"+str(bones.left_forearm.x_val)+"\t"+str(bones.left_forearm.y_val)+"\t"+str(bones.left_forearm.z_val)+"\t"+str(bones.left_hand.x_val)+"\t"+str(bones.left_hand.y_val)+"\t"+str(bones.left_hand.z_val)+"\t"+str(bones.right_arm.x_val)+"\t"+str(bones.right_arm.y_val)+"\t"+str(bones.right_arm.z_val)+"\t"+str(bones.right_forearm.x_val)+"\t"+str(bones.right_forearm.y_val)+"\t"+str(bones.right_forearm.z_val)+"\t"+str(bones.right_hand.x_val)+"\t"+str(bones.right_hand.y_val)+"\t"+str(bones.right_hand.z_val)+"\t"+str(bones.right_hand_tip.x_val)+"\t"+str(bones.right_hand_tip.y_val)+"\t"+str(bones.right_hand_tip.z_val)+"\t"+str(bones.left_hand_tip.x_val)+"\t"+str(bones.left_hand_tip.y_val)+"\t"+str(bones.left_hand_tip.z_val)+"\t"+str(bones.right_foot_tip.x_val)+"\t"+str(bones.right_foot_tip.y_val)+"\t"+str(bones.right_foot_tip.z_val)+"\t"+str(bones.left_foot_tip.x_val)+"\t"+str(bones.left_foot_tip.y_val)+"\t"+str(bones.left_foot_tip.z_val)+"\n"
    f_output.write(line)
def doNothing(x):
    pass
