apiVersion: v1
kind: Pod
metadata:
  name: kicirogl-airsim
  labels:
    user: kicirogl
    priority: "1"
spec:
  restartPolicy: Never
  containers:
    - name: airsim-1
      image: ic-registry.epfl.ch/cvlab/kicirogl/kicirogl-airsim:latest
      imagePullPolicy: Always # load the newest version of the image
      #command: ["/opt/lab/setup_and_wait.sh"] 
      #   this one will do nothing and wait, so you can enter the container yourself with
      #   kubectl exec -it pod_name /bin/bash
      command: ["/bin/bash"]
      args: ["-c", "/opt/lab/setup_and_wait.sh"]

      #- "/opt/lab/setup_and_run_command.sh"
      #- "cd /cvlabdata2/home/lis/kubernetes_example && python job_example.py"
      # runs the command on the 2nd line

      env:
      - name: CLUSTER_USER
        value: "kicirogl"
      - name: CLUSTER_USER_ID
        value: "177197" 
      - name: CLUSTER_GROUP_NAME
        value: "CVLAB-unit"
      - name: CLUSTER_GROUP_ID
        value: "11166"
          
      volumeMounts:
        - mountPath: /cvlabdata2
          name: cvlabdata2
        - mountPath: /dev/shm
          name: dshm

      # specify that it uses a GPU!
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  
  volumes:
    - name: cvlabdata2
      persistentVolumeClaim:
        claimName: pv-cvlabdata2
    
    # shared memory, often needed by PyTorch dataloaders
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
