ARG BASE_IMAGE=nvidia/cudagl:10.0-devel-ubuntu18.04
FROM $BASE_IMAGE

USER root
RUN apt-get update
RUN apt-get install \
	rsync \
    sudo \
    wget \
    x11-xserver-utils \
    git \ 
    -y --no-install-recommends 
